// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PlanningSystem.Data
{
    public partial class ConfirmedStat
    {
        public int Id { get; set; }
        public int Simulid { get; set; }
        public DateTime TargetDate { get; set; }
        public string Tier { get; set; }
        public int? Tierid { get; set; }
        public int? CountOfcust { get; set; }
        public string SalesAmount { get; set; }
        public string CustProp { get; set; }
        public string SalesProp { get; set; }
        public double? CreditPoint { get; set; }
    }
}