// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PlanningSystem.Data
{
    public partial class CreditDetail
    {
        public int Ruleid { get; set; }
        public string CustCode { get; set; }
        public int? Point { get; set; }
        public string PayTerm { get; set; }
        public decimal? AltArratio { get; set; }
        public int AltarratioPoint { get; set; }
        public int BounceCntYear { get; set; }
        public int BounceCntYearPoint { get; set; }
        public decimal ReturnAvgMonth { get; set; }
        public int ReturnAvgPoint { get; set; }
    }
}