// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PlanningSystem.Data
{
    public partial class CreditRuleDetail
    {
        public int Detailid { get; set; }
        public int Ruleid { get; set; }
        public int Ruleno { get; set; }
        public string Altarratio { get; set; }
        public float? AltarratioPoint { get; set; }
        public string Bounce { get; set; }
        public float? BouncePoint { get; set; }
        public string Return { get; set; }
        public float? ReturnPoint { get; set; }
        public DateTime Createdate { get; set; }

        public virtual CreditRuleHead Rule { get; set; }
    }
}