// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PlanningSystem.Data
{
    public partial class CustAssessResultTable
    {
        public int Resultid { get; set; }
        public DateTime TargetDate { get; set; }
        public string CustCode { get; set; }
        public string CustName { get; set; }
        public string Customercategory2 { get; set; }
        public string ChainName { get; set; }
        public string CountryRegionId { get; set; }
        public string State { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public long SalesTeamId { get; set; }
        public string Custgroup { get; set; }
        public int Custgradeid { get; set; }
        public decimal? Custfirstyear { get; set; }
        public decimal? Custsecondyear { get; set; }
        public decimal? UsingCustavg { get; set; }
        public decimal? TwoYearSalesAmt { get; set; }
        public decimal? FirstYearSalesAmt { get; set; }
        public decimal? SecondYearSalesAmt { get; set; }
        public decimal? UsingAvg { get; set; }
        public string Tier { get; set; }
        public string SuggestTier { get; set; }
        public string Reason { get; set; }
        public string SalesRequestTier { get; set; }
        public string SalesReason { get; set; }
        public string Axtier { get; set; }
        public string FinalTier { get; set; }
        public DateTime CreatDate { get; set; }
    }
}