// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PlanningSystem.Data
{
    public partial class Factor
    {
        public long Factorid { get; set; }
        public string Factorname { get; set; }
        public string Facotrdescription { get; set; }
        public DateTime Createdate { get; set; }
        public string Createdby { get; set; }
        public DateTime Modifieddate { get; set; }
        public string Modifiedby { get; set; }
    }
}