// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PlanningSystem.Data
{
    public partial class PlanDetail
    {
        public long PlanDetailid { get; set; }
        public long PlanHeadid { get; set; }
        public long Factorid { get; set; }
        public string Factorname { get; set; }
        public string Factordescription { get; set; }
        public DateTime Createdate { get; set; }
    }
}