// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PlanningSystem.Data
{
    public partial class PlanHead
    {
        public long Planid { get; set; }
        public string Planname { get; set; }
        public string Plandescription { get; set; }
        public int? Factorcount { get; set; }
        public DateTime Createdate { get; set; }
        public string Createdby { get; set; }
        public DateTime Modifieddate { get; set; }
        public string Modifiedby { get; set; }
    }
}