// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PlanningSystem.Data
{
    public partial class SalesTeam
    {
        public int TeamId { get; set; }
        public string SalesTeamId { get; set; }
    }
}