// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PlanningSystem.Data
{
    public partial class TierPlanDetail
    {
        public long Tierdetailid { get; set; }
        public long Tierplanid { get; set; }
        public int? Tierid { get; set; }
        public string Tiername { get; set; }
        public float? Salesamountrule { get; set; }
        public float? Creditscorerule { get; set; }
        public DateTime Createdate { get; set; }
    }
}