// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PlanningSystem.Data
{
    public partial class TierPlanHead
    {
        public long Tierplanid { get; set; }
        public string Tierplanname { get; set; }
        public string Tierplandescription { get; set; }
        public int Tiercount { get; set; }
        public DateTime Createdate { get; set; }
        public string Createdby { get; set; }
        public DateTime Modifieddate { get; set; }
        public string Modifiedby { get; set; }
    }
}